### ISSUE TITLE
Generation of output using a Metanorma XML file doesn't work with ones that need images

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-cli#11] opened 2018-10-30 08:34 UTC
Sample attached.
[csd-tofix.zip](https://github.com/riboseinc/metanorma-cli/files/2528708/csd-tofix.zip)

**Comment by opoudjis** [comment] 2018-10-30 11:57
This is compiling fine my side: I am attaching the results of `metanorma -t csd csd-general-recurrence.xml`, and both the HTML and the DOC file are generating images as expected. I cannot replicate your problem.

[csd-tofix 2.zip](https://github.com/riboseinc/metanorma-cli/files/2529503/csd-tofix.2.zip)

**Comment by ronaldtse** [comment] 2018-10-31 04:57
Can you compile the document in context of the standards.calconnect.org repo? i.e.

```sh
mv csd-tofix/* csd/
make dist-clean all
```

Thanks!

**Comment by opoudjis** [comment] 2018-10-31 06:33
The issue is running metanorma -t outside the local directory, as is done in the makefile (`metanorma -t csd -R csd/csd-general-recurrence.rxl -x html,pdf,doc,xml csd/csd-general-recurrence.xml`): the path to the images is not being constructed to account for it.

**Comment by opoudjis** [comment] 2018-10-31 08:52
Modifying isodoc: if the filename being processed is dir/file.xml, then any images within the file need to have their location prefixed with dir, for the gem to find them.

**Comment by opoudjis** [comment] 2018-10-31 09:22
Also need to modify Html2Doc: if the filename is dir/file.doc, then any images to be processed need to have their location prefixed by dir in order to be accessed.

**Comment by opoudjis** [comment] 2018-10-31 10:41
Extends to header location as well.

**Comment by opoudjis** [comment] 2018-10-31 10:49
Fixed in isodoc and html2doc, and published gem updates.

**Closed by opoudjis** 2018-10-31 10:49 UTC
Labels: bug

**Comment by ronaldtse** [comment] 2018-11-01 11:15
Thank you sir!
